version: '3.7'

services:
  sabres_node:
    build: .
    image: 'sabres_node:latest'
    ports:
      - '3000'
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge